name: Manual workflow testing

on: workflow_dispatch

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Extract Tagging
      id: tag
      run: |
        echo ${{github.ref_name}}
        echo "tag=${{github.ref_name}}" >> $GITHUB_OUTPUT
        echo ${{github.event.release.tag_name}}
    - name: show tagging
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}
        
    - name: Update Version in setup.py
      run: >-
        sed "s/{{VERSION_VAR}}/${{ steps.tag.outputs.TAG_NAME }}/g" setup.py
