name: Manual workflow testing

on: workflow_dispatch

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Extract Tagging
      id: tag
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: show tagging
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        
    - name: Update Version in setup.py
      run: >-
        sed "s/{{VERSION_VAR}}/${{ env.RELEASE_VERSION }}/g" setup.py
